# Generated by Django 4.2.7 on 2023-11-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bmilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmilog',
            name='log_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
