# Generated by Django 4.2.7 on 2023-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231127_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_burned_per_set',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
