# Generated by Django 4.2.7 on 2023-12-01 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_exerciselog_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_trainer',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'user_type': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
